# Generated by Django 3.0.2 on 2020-02-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20200211_0709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set(),
        ),
    ]
