# Generated by Django 3.0.2 on 2020-02-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20200211_0714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('name', 'version')},
        ),
    ]
