# Generated by Django 3.0.2 on 2020-02-11 07:28

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0004_auto_20200211_0724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="sample_context_data",
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
