# Generated by Django 3.0.3 on 2020-05-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templatestore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="templateconfig",
            name="attributes",
            field=models.CharField(default="{}", max_length=1000),
        ),
    ]
