# Generated by Django 3.0.7 on 2020-06-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("templatestore", "0003_auto_20200608_2208"),
        ("templatestore", "0003_templateversion_version_alias"),
    ]

    operations = []
