# Generated by Django 3.2.7 on 2022-02-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatestore', '0008_migrate_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateversion',
            name='tiny_url',
            field=models.JSONField(default=None, null=True),
        ),
    ]
