<<<<<<< HEAD:templatestore/migrations/0009_templateversion_tiny_urlV5.py
# Generated by Django 3.2.7 on 2022-03-03 12:53
=======
# Generated by Django 3.2.7 on 2022-03-06 17:36
>>>>>>> 52f28242f3aa564151166438483dd392940bb04a:templatestore/migrations/0009_templateversion_tiny_url.py

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatestore', '0008_migrate_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateversion',
            name='tiny_url',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
