# Generated by Django 3.0.7 on 2022-06-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatestore', '0009_templateversion_tiny_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateconfig',
            name='optional',
            field=models.BooleanField(default=False),
        ),
    ]
