# Generated by Django 3.2.7 on 2022-03-04 05:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatestore', '0009_templateversion_tiny_urlV5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateversion',
            name='tiny_url',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
