# Generated by Django 3.2.7 on 2022-03-03 11:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatestore', '0010_alter_templateversion_tiny_url_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateversion',
            name='tiny_url',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
