# Generated by Django 3.2.7 on 2022-02-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatestore', '0012_alter_templateversion_tiny_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateversion',
            name='tiny_url',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
